dist: bionic
language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - 1.x

script:
  - go vet ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

before_install:
  - sudo apt-get install libwebp-dev
  - go mod vendor -v

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    update: true
